import java.sql.*;
import java.util.List;

import repositories.IRepository;

import domain.Seller;



public class Main {

	public static void main(String[] args) {
	}
	}

	/*	String url     	= "jdbc:mysql://localhost";
		String user 	= "root";
		String password = "";
		Seller jnowak 	= new Seller();
		jnowak.setEmail	("aurbanow");
		jnowak.setPesel	("qwerty");
		
		
		try
		{
			Class.forName("com.mysql.jdbc.Driver").newInstance();
			Connection connection = DriverManager.getConnection(url);
			
			Statement stt = connection.createStatement();
			
			stt.execute("DROP DATABASE IF EXITS shop");
			stt.execute("CREATE DATABASE shop");
			stt.execute("USE shop");
			
			stt.execute("DROP TABLE IF EXITS seller");
			stt.execute("CREATE TABLE seller (" +
					"id INT NOT NULL AUTO_INCREMENT," +
					"email TEXT," +
					"pesel INT," +
					"PRIARY KEY(id)" +
					");");
			
			IRepository<Seller> sellers = new SellerRepository(connection);
			sellers.add(jnowak);
			List<Seller> sellersFromDB= sellers.getAll();
			
			for(Seller sellerFromDB: sellersFromDB)
				System.out.println(sellerFromDB.getId()+" "+sellerFromDB.getEmail()+" "+sellerFromDB.getPesel());
			
			Seller s = sellers.get(2);
			s.setPesel("90090811232");
			sellers.update(s);
			sellers.delete(sellersFromDB.get(0));
			
			for(Seller sellerFromDB: sellers.getAll())
				System.out.println(sellerFromDB.getId()+" "+sellerFromDB.getEmail()+" "+sellerFromDB.getPesel());
			
			
			
			connection.close();
		}
		catch (Exception e)
		{
			e.printStackTrace();				
		}
	}
}
		
		String url="jdbc:hsqldb:hsql://localhost/Shop";
		Seller jnowak = new Seller();
		jnowak.setEmail("aurbanow");
		jnowak.setPesel("qwerty");
		
		try {
			
			Connection connection = DriverManager.getConnection(url);
		
			 CREATE  TABLE  IF NOT EXISTS "main"."Seller" ("id" INTEGER PRIMARY KEY  NOT NULL , "email" TEXT, "pesel" INTEGER)
			String createTableSql = 
					"CREATE TABLE users("
					+ "id int GENERATED BY DEFAULT AS IDENTITY,"
					+ "login VARCHAR(20),"
					+ "password VARCHAR(20)"
					+ ")";
			Statement createTable = connection.createStatement();
			createTable.executeUpdate(createTableSql);
			
			IRepository<Seller> sellers = new SellerRepository(connection);
			sellers.add(jnowak);
			List<Seller> sellersFromDB= sellers.getAll();
			
			for(Seller sellerFromDB: sellersFromDB)
				System.out.println(sellerFromDB.getId()+" "+sellerFromDB.getEmail()+" "+sellerFromDB.getPesel());
			
			Seller s = sellers.get(2);
			s.setPesel("90090811232");
			sellers.update(s);
			sellers.delete(sellersFromDB.get(0));
			
			for(Seller sellerFromDB: sellers.getAll())
				System.out.println(sellerFromDB.getId()+" "+sellerFromDB.getEmail()+" "+sellerFromDB.getPesel());
			
			
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
		System.out.println("koniec");
	}
*/